cnoe-io/ai-platform-engineering

- docs/docusaurus.config.ts
> fix(docs): update edit links

- .github/workflows/publish-gh-pages.yml
- README.md
- docs/README.md
> fix(docs): updates

- helm/Chart.yaml
- helm/charts/agent/templates/_helpers.tpl
- helm/charts/agent/templates/deployment.yaml
- helm/values-external-secrets.yaml.example
- helm/values.yaml
- Add two new sub charts:
- multi-agent system `ai-platform-engineer`
- backstage-agent-forge
- helm template tested locally
> feature: add multi-agent and agent-forge to helm chart

- ai_platform_engineering/agents/komodor/agent_komodor/__main__.py
- ai_platform_engineering/agents/komodor/agent_komodor/protocol_bindings/a2a_server/__main__.py
- ai_platform_engineering/agents/webex/agent_webex/protocol_bindings/a2a_server/__main__.py
Currently failing the lint tests due to unused imports: https://github.com/cnoe-io/ai-platform-engineering/actions/runs/16267102299/job/45925190965
> fix: ruff linter fails

- docker-compose.yaml
- docs/docs/getting-started/local-development.md
- docs/docs/getting-started/next-steps.md
- docs/docs/getting-started/user-interfaces.md
- docs/sidebars.ts
- helm/Chart.yaml
- helm/values-existing-secrets.yaml
- helm/values-ingress.yaml.example
- helm/values-secrets.yaml.example
- helm/values.yaml
> fix(atlassian): remove agent-atlassian

- docker-compose.dev.yaml
Add profiles for graph_rag services in ai-platform-engineer docker-compose
> fix: add profiles to graph_rag/nexigraph services

- docs/docs/getting-started/idpbuilder/setup.md
- docs/sidebars.ts
Add docs for how to setup a kind cluster using idpbuilder.
> feat: add idpbuilder docs

- docs/docs/getting-started/idpbuilder/setup.md
- docs/src/css/custom.css
Improve IDPBuilder doc.
1. Added a diagram:
2. More details about configuring LLM secrets in Vault with your chosen LLM provider:
> chore: improve idpbuilder doc with diagram and llm configuration details

- docs/docs/getting-started/idpbuilder/setup.md
> fix(ipdbuilder): update idpbuild docs

- helm/charts/agent/templates/_helpers.tpl
- helm/charts/agent/templates/mcp-deployment.yaml
- helm/charts/agent/templates/mcp-service.yaml
> fix: correct release name use and clean up

- .github/workflows/helm-pre-release.yml
- ai_platform_engineering/agents/template/agent_petstore/a2a_agent_client/agent.py
- ai_platform_engineering/agents/template/agent_petstore/a2a_agent_client/agentcard.py
- ai_platform_engineering/agents/template/agent_petstore/protocol_bindings/mcp_server/mcp_petstore/server.py
- ai_platform_engineering/agents/template/uv.lock
- ai_platform_engineering/multi_agents/platform_engineer/protocol_bindings/a2a/agent.py
- docs/docs/getting-started/idpbuilder/setup.md
**Description:**
This PR introduces Agent-to-Agent (A2A) protocol support to the template agent, enabling seamless interoperability with the broader agent ecosystem.
**Changes Made:
New Files Added:**
agent_petstore/a2a_agent_client/agentcard.py
– Defines the template agent's metadata, skills, and capabilities for discovery by other agents.
agent_petstore/a2a_agent_client/agent.py
– Sets up the template agent's runtime logic and handles tool registration for A2A communication.
**Modified Files:**
agent_petstore/protocol_bindings/mcp_server/mcp_petstore/server.py
– Fixed incorrect Python import statements (e.g., pet_findByStatus.py vs pet_findbystatus) that were preventing server 
startup.
**What This Enables:**
The template agent can now be discovered and connected to using the A2A …
> Template integration

- .dockerignore
- ai_platform_engineering/agents/slack/uv.lock
- integration/test_prompts_detailed.yaml
> fix: docker latest images with uv.lock

- .dockerignore
> fix: removing knowledge base from .dockerignore

- ai_platform_engineering/agents/argocd/mcp/mcp_argocd/api/client.py
- ai_platform_engineering/agents/argocd/uv.lock
> fix(argocd): add VERIFY_SSL and ARGOCD_VERIFY_SSL support in mcp

- .gitignore
- ai_platform_engineering/knowledge_bases/rag/build/Dockerfile.web
- ai_platform_engineering/knowledge_bases/rag/kb_rag/protocol_bindings/a2a_server/agent.py
- ai_platform_engineering/knowledge_bases/rag/server/loader/loader.py
- ai_platform_engineering/knowledge_bases/rag/server/rag_api.py
- ai_platform_engineering/knowledge_bases/rag/web/index.html
- ai_platform_engineering/knowledge_bases/rag/web/nginx.conf
- ai_platform_engineering/knowledge_bases/rag/web/package-lock.json
- ai_platform_engineering/knowledge_bases/rag/web/package.json
- ai_platform_engineering/knowledge_bases/rag/web/postcss.config.js
- ai_platform_engineering/knowledge_bases/rag/web/src/index.css
- ai_platform_engineering/knowledge_bases/rag/web/src/main.tsx
- ai_platform_engineering/knowledge_bases/rag/web/src/ui/App.tsx
- ai_platform_engineering/knowledge_bases/rag/web/tailwind.config.js
- ai_platform_engineering/knowledge_bases/rag/web/tsconfig.json
- ai_platform_engineering/knowledge_bases/rag/web/vite.config.ts
- docker-compose.yaml
- prompt_config.yaml
> feat: adding frontend UI to kb-rag, now forms agent, server and web

- ai_platform_engineering/agents/argocd/agent_argocd/protocol_bindings/a2a_server/agent.py
- ai_platform_engineering/agents/argocd/mcp/mcp_argocd/server.py
- ai_platform_engineering/agents/argocd/mcp/mcp_argocd/tools/api_v1_applications.py
- ai_platform_engineering/agents/argocd/mcp/mcp_argocd/tools/api_v1_applications_name_logs.py
- ai_platform_engineering/agents/webex/pyproject.toml
- ai_platform_engineering/agents/webex/uv.lock
- ai_platform_engineering/multi_agents/pyproject.toml
- ai_platform_engineering/multi_agents/uv.lock
- pyproject.toml
- uv.lock
> fix: lint errors and argocd mcp bugs

- README.md
> fix(README.md): add star history

- ai_platform_engineering/agents/weather/agent_weather/protocol_bindings/a2a_server/agent.py
- ai_platform_engineering/multi_agents/platform_engineer/protocol_bindings/a2a/agent.py
- prompt_config.yaml
- slim-config.yaml
> fix(petstore/weather): bug fixes

- ai_platform_engineering/knowledge_bases/rag/kb_rag/__main__.py
- ai_platform_engineering/knowledge_bases/rag/kb_rag/protocol_bindings/a2a_server/agent.py
- ai_platform_engineering/knowledge_bases/rag/server/loader/loader.py
- workshop/docker-compose.mission4.yaml
- Fixes a crash with RAG ingestion, when a document is non chunked (but previous one was chunked)
- RAG agent now only initialises Vector store when the agent is invoked
- Removed additional invocation of LLM chain in RAG agent
- Update workshop mission4 with correct env vars
> fix: rag ingestion crash; workshop docker file

- workshop/docker-compose.mission4.yaml
Switch workshop mission4 to a different env file
> fix(workshop): switch mission4 to a different env file

- docs/docs/knowledge_bases/rag.md
- docs/docs/knowledge_bases/ragingestion.md
- workshop/docker-compose.mission4.yaml
> fix(workshop): mission4: add restart policy to docker compose

- .github/workflows/kb-rag-docker-build.yml
- ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph/agent_graph_gen/src/agent_graph_gen/agent.py
- ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph/agent_graph_gen/uv.lock
- ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph/agent_graph_qa/src/agent_graph_qa/agent.py
- ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph/core/src/core/agent/tools.py
- ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph/server/uv.lock
- ai_platform_engineering/knowledge_bases/rag/.dockerignore
- ai_platform_engineering/knowledge_bases/rag/kb_rag/protocol_bindings/a2a_server/agent.py
- ai_platform_engineering/knowledge_bases/rag/pyproject.toml
- ai_platform_engineering/knowledge_bases/rag/server/loader/loader.py
- ai_platform_engineering/knowledge_bases/rag/server/rag_api.py
- ai_platform_engineering/knowledge_bases/rag/uv.lock
- ai_platform_engineering/knowledge_bases/rag/web/src/ui/App.tsx
- docker-compose.yaml
- prompt_config.yaml
references.
- [] Existing issues have been referenced (where applicable)
> feat: adding reranking and redis db management with kb-rag 

- ai_platform_engineering/agents/aws/clients/a2a/agent.py
- ai_platform_engineering/agents/aws/clients/slim/agent.py
- ai_platform_engineering/multi_agents/__init__.py
- ai_platform_engineering/multi_agents/platform_engineer/__init__.py
- docker-compose.yaml
- prompt_config.yaml
Added the aws agent to the platform engineer
> feat: add the aws agent to platform engineer

- helm/Chart.yaml
- helm/charts/kb-rag-stack/Chart.yaml
- helm/charts/kb-rag-stack/charts/kb-rag-redis/Chart.yaml
- helm/charts/kb-rag-stack/charts/kb-rag-redis/templates/service.yaml
- Change service targetPort from 'http' to 'redis' to match container port name
- Change service port name from 'http' to 'redis' for consistency
- Fixes Redis connectivity issue where service had no endpoints
BREAKING CHANGE: Redis service port name changed from 'http' to 'redis'
references.
> fix(kb-rag-redis): correct service port configuration to match deployment

- ai_platform_engineering/knowledge_bases/rag/server/loader/loader.py
The kb-rag-server was experiencing OOMKilled errors when processing large sitemaps (1072 pages) because it loaded all pages into memory simultaneously using `ascrape_all()`.
- `ascrape_all(urls)` loads all 1072 pages into memory at once (~4-8GB)
- No memory management between page processing
- Container gets OOMKilled even with 8GB memory limit
- Replace batch loading with streaming: `ascrape(page_url)` processes one page at a time
- Add garbage collection after each page to free memory
- Add error handling to continue processing on individual page failures
- Memory usage drops from 4-8GB to 4-8MB per page
- Tested with platform-docs.outshift.io sitemap (1072 pages)
- No more OOMKilled errors
- Maintains same functionality with better memory efficiency
Fixes the OOMKilled containers …
> fix: optimize memory usage by streaming page processing

- ai_platform_engineering/knowledge_bases/rag/pyproject.toml
- ai_platform_engineering/knowledge_bases/rag/server/loader/loader.py
- ai_platform_engineering/knowledge_bases/rag/server/loader/loader.py.bk
- ai_platform_engineering/knowledge_bases/rag/tests/README_memory_test.md
- ai_platform_engineering/knowledge_bases/rag/tests/platform_docs_memory_optimization.py
- ai_platform_engineering/knowledge_bases/rag/tests/run_hybrid_tests.py
- ai_platform_engineering/knowledge_bases/rag/tests/run_memory_test.py
- ai_platform_engineering/knowledge_bases/rag/tests/test_hybrid_loader.py
- ai_platform_engineering/knowledge_bases/rag/tests/test_integration_hybrid.py
- ai_platform_engineering/knowledge_bases/rag/tests/test_loader.py
- ai_platform_engineering/knowledge_bases/rag/tests/test_scale_ingestion.py
- ai_platform_engineering/knowledge_bases/rag/tests/test_simple_hybrid.py
- ai_platform_engineering/knowledge_bases/rag/uv.lock
- pyproject.toml
- uv.lock
- Add configurable batch size via URL_BATCH_SIZE environment variable (default: 5)
- Replace single URL processing with batch processing to balance memory usage and efficiency
- Fix asyncio compatibility issues by using asyncio.to_thread for WebBaseLoader
- Remove custom_parser dependency on BeautifulSoup objects
- Add set_batch_size() method for runtime configuration
- Implement garbage collection after each batch to free memory
- Add comprehensive test suite for memory optimization
- Include documentation and examples for the new batch processing feature
Key improvements:
- Prevents memory overflow when processing large sitemaps (1000+ URLs)
- Configurable batch sizes for different memory constraints
- Maintains processing efficiency while controlling memory usage
- Proper error …
> feat: implement memory-optimized batch processing for URL loading

- helm/Chart.lock
- helm/Chart.yaml
- helm/charts/kb-rag-stack/Chart.lock
- helm/charts/kb-rag-stack/Chart.yaml
- helm/charts/kb-rag-stack/charts/kb-rag-server/Chart.yaml
- helm/charts/kb-rag-stack/charts/kb-rag-server/values.yaml
> fix: no default env in kb-rag-server chart

- docker-compose.dev.yaml
> fix(docker-compose.dev): add p2p-tracing profile to nexigraph

- ai_platform_engineering/agents/aws/README.md
- ai_platform_engineering/agents/aws/agent_aws/__init__.py
- ai_platform_engineering/agents/aws/agent_aws/__main__.py
- ai_platform_engineering/agents/aws/agent_aws/agent.py
- ai_platform_engineering/agents/aws/agent_aws/protocol_bindings/a2a_server/__main__.py
- ai_platform_engineering/agents/aws/build/Dockerfile.a2a
- ai_platform_engineering/agents/aws/clients/a2a/agent.py
- ai_platform_engineering/agents/aws/pyproject.toml
- ai_platform_engineering/agents/aws/requirements.txt
- ai_platform_engineering/agents/aws/uv.lock
- docker-compose.dev.yaml
- docker-compose.yaml
- prompt_config.yaml
Fixed the docker compose file so that it's building the correct dockerfile for the aws agent and use the remote image of the platform engineer.
Added the IAM AWS MCP so that the aws agent now has 3 MCPs
*A stable image of the aws-agent needs to be created.
> IAM MCP added to AWS agent

- .github/workflows/agent-a2a-pre-release.yaml
- .github/workflows/agent-mcp-docker-build.yml
- .github/workflows/agent-mcp-pre-release.yaml
- .github/workflows/supervisor-agent-pre-release.yaml
> feat: add litellm and prebuild docker image github actions

- .github/workflows/agent-a2a-docker-build.yml
- .github/workflows/agent-mcp-docker-build.yml
- .github/workflows/quick-sanity-integration-tests-dev.yml
- .github/workflows/quick-sanity-integration-tests-latest.yml
- .github/workflows/quick-sanity-integration-tests-stable.yml
- Add quick sanity integration tests for latest, stable, and dev tag environments
- Implement automated stable tag creation with conditional test triggering
- Enhance A2A agent Docker builds with intelligent change detection and multi-platform support
- Add MCP agent Docker builds with path-based filtering for mcp/ directories only
- Configure comprehensive environment variable management from GitHub secrets
- Add build matrix optimization to skip unchanged agents and reduce CI overhead
- Implement artifact logging and workspace cleanup for better resource management
> feat: add integration test workflows and improve agent Docker build automation

- workshop/docker-compose.mission4.yaml
Fix the workshop4 to a specific tag
> fix: fix workshop4 to specific version

- ai_platform_engineering/multi_agents/platform_engineer/protocol_bindings/a2a/agent.py
> fix: for now always set is_task_complete as True in order to avoid Queue is closed error
